### ISSUE TITLE
scene

### ISSUE THREAD

**Issue by Lyr3x** [madgeni/alexa_domo#1] opened 2016-10-24 10:59 UTC
so after a lot of debugging: the scenes and groups are not discovered, when they have the same idx... I know that the scene idx and devIdx are stored in different tables but there is a conflict when the function want to add them. I saw in the logs that my devIdx=2 added 2 times instead of 1 time devIdx=2 and scene idx=2

**Comment by Lyr3x** [comment] 2016-10-24 17:10
i edited the scene db entry manually and set the id to 220.. but the scene isnt caught at all

**Comment by Nesurion** [comment] 2016-10-24 17:12
I have the same issue. I tried to dig a bit into detail and looks to me like the problem is this:
in https://github.com/madgeni/alexa_domo/blob/master/domapi.js#L364 all devices in a room are returned (including groups).
The problem is, that one of my lamps has the same id as a group. So the _DeviceIDs_ array contains the same ID twice.
When getting the device information in line https://github.com/madgeni/alexa_domo/blob/master/domapi.js#L189 the same idx (one for the group and one for the device) are used. Since the getDevice api call does not support getting group information, the information about the device is added twice and not the group.

I tried chaning the idx to (idx + 200) if the device is a group. (https://github.com/madgeni/alexa_domo/blob/master/domapi.js#L362)
But as I said the getDevice call does not support groups, so the call returns an error.

I'm by no means a JavaScript expert, so there might be an easy solution to this, that I just can't come up with.

**Comment by madgeni** [comment] 2016-10-25 18:15
So is the issue in this case that if a group is in a room plan it’s not then being discovered? If so, i’ll take a look into it

**Comment by madgeni** [comment] 2016-10-25 18:17
Hi - 
it only finds groups, not scenes - is yours a scene or a group?

**Comment by Lyr3x** [comment] 2016-10-25 18:31
The discovery do not find groups nor scenes... but there is not a big difference between scenes and groups in domoticz: both are tagged as a type=1 device in a room plan:
 `{
         "DevSceneRowID" : "3",
         "Name" : "[Scene] testGroup",
         "devidx" : "3",
         "idx" : "41",
         "order" : "41",
         "type" : 1
      },
{
         "DevSceneRowID" : "2",
         "Name" : "[Scene] Kinomodus",
         "devidx" : "2",
         "idx" : "22",
         "order" : "23",
         "type" : 1
      }`

But they have different types when you ask for you scenes and groups with /json.htm?type=scenes:
`{
         "Description" : "",
         "Favorite" : 1,
         "LastUpdate" : "2016-10-24 23:05:24",
         "Name" : "Kinomodus",
         "OffAction" : "",
         "OnAction" : "",
         "Protected" : false,
         "Status" : "Off",
         "Timers" : "false",
         "Type" : "Group",
         "UsedByCamera" : false,
         "idx" : "2"
      },
      {
         "Description" : "",
         "Favorite" : 0,
         "LastUpdate" : "2016-10-25 20:26:13",
         "Name" : "testGroup",
         "OffAction" : "",
         "OnAction" : "",
         "Protected" : false,
         "Status" : "Off",
         "Timers" : "false",
         "Type" : "Scene",
         "UsedByCamera" : false,
         "idx" : "3"
      }
   ],`

**Comment by madgeni** [comment] 2016-10-25 18:35
Have you tried the latest version?

**Comment by Lyr3x** [comment] 2016-10-25 18:42
edit: maybe there is a different bug in my setup. brb

ahh. i didnt saw the latest commit... when i test the discovery function in lambda i see the scene:
`{
        "applianceId": 202,
        "manufacturerName": "Kinomodus",
        "modelName": "Kinomodus",
        "version": "2",
        "friendlyName": "Kinomodus",
        "isReachable": true,
        "actions": [
          "turnOn",
          "turnOff"
        ],
        "additionalApplianceDetails": {
          "WhatAmI": "scene"
        }
      },`

but alexa wont discover this guy

**Comment by madgeni** [comment] 2016-10-25 18:45
Dammit, I'll take a look tomorrow

**Comment by madgeni** [comment] 2016-10-25 18:45
Does it discover the rest?

**Comment by Lyr3x** [comment] 2016-10-25 18:46
strange, no it discover nothing now 💃

**Comment by madgeni** [comment] 2016-10-25 18:47
Whoops. Sure it's something simple. Will take a look as soon as I can.

**Comment by Lyr3x** [comment] 2016-10-25 18:56
Ah its not your fault:
The language you selected does not match your Amazon account settings.

As a result, Alexa skills are not available.

To get the best Alexa experience, please choose German by selecting continue

german english conflict in here...

need to wait for the invitation and the echo..

**Comment by madgeni** [comment] 2016-10-25 21:56
Boo!
Would it work if I added German into the skill?

**Comment by Lyr3x** [comment] 2016-10-26 06:14
Do you manually need to add language stuff?

**Comment by madgeni** [comment] 2016-10-26 11:38
Closing the issue around scenes (groups really) as it's now fixed

**Closed as completed by madgeni** 2016-10-26 11:38 UTC

**Comment by madgeni** [comment] 2016-10-26 15:41
amazon introduced German into the Smart Home Skill (you should see a tab when you create it)
